// 常見不規則變化 → 基本形(直接查與字尾還原都失敗時的退路)
export const IRREGULARS: Record<string, string> = {
  am: 'be', is: 'be', are: 'be', was: 'be', were: 'be', been: 'be', being: 'be',
  has: 'have', had: 'have', having: 'have',
  does: 'do', did: 'do', done: 'do', doing: 'do',
  went: 'go', gone: 'go', goes: 'go',
  made: 'make', said: 'say', saw: 'see', seen: 'see',
  took: 'take', taken: 'take', got: 'get', gotten: 'get',
  gave: 'give', given: 'give', came: 'come', knew: 'know', known: 'know',
  thought: 'think', found: 'find', told: 'tell', became: 'become',
  left: 'leave', felt: 'feel', brought: 'bring', began: 'begin', begun: 'begin',
  kept: 'keep', held: 'hold', wrote: 'write', written: 'write',
  stood: 'stand', heard: 'hear', meant: 'mean', met: 'meet', ran: 'run',
  paid: 'pay', sat: 'sit', spoke: 'speak', spoken: 'speak', led: 'lead',
  grew: 'grow', grown: 'grow', lost: 'lose', fell: 'fall', fallen: 'fall',
  sent: 'send', bought: 'buy', built: 'build', understood: 'understand',
  drew: 'draw', drawn: 'draw', broke: 'break', broken: 'break',
  spent: 'spend', wore: 'wear', worn: 'wear', chose: 'choose', chosen: 'choose',
  ate: 'eat', eaten: 'eat', drank: 'drink', drunk: 'drink',
  drove: 'drive', driven: 'drive', flew: 'fly', flown: 'fly',
  forgot: 'forget', forgotten: 'forget', slept: 'sleep', taught: 'teach',
  caught: 'catch', sold: 'sell', woke: 'wake', woken: 'wake',
  rose: 'rise', risen: 'rise', threw: 'throw', thrown: 'throw', shown: 'show',
  hidden: 'hide', hid: 'hide', rode: 'ride', ridden: 'ride', won: 'win',
  sang: 'sing', sung: 'sing', swam: 'swim', swum: 'swim',
  children: 'child', men: 'man', women: 'woman', feet: 'foot', teeth: 'tooth',
  mice: 'mouse', lives: 'life', leaves: 'leaf',
  better: 'good', best: 'good', worse: 'bad', worst: 'bad',
  less: 'little', least: 'little', further: 'far', farther: 'far',
};
